--5.1 Створити таблицю описів значень атрибутів екземплярів об'єктів.
CREATE TABLE ATTRIBUTES (
	ATTR_ID NUMBER(10),
	OBJECT_ID NUMBER(20),
	VALUE VARCHAR2(4000),
	DATE_VALUE DATE,
	LIST_VALUE_ID NUMBER(10)
);  

ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_PK
	PRIMARY KEY (ATTR_ID, OBJECT_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_LIST_VALUE_ID_FK
	FOREIGN KEY (LIST_VALUE_ID) REFERENCES LISTS (LIST_VALUE_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_ATTR_ID_FK
	FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_OBJECT_ID_FK
	FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID);

--5.2 На основі вмісту двох рядків двох таблиць, заповнених у лабораторній 
--роботі No3, та опису атрибутів екземплярів об'єктів, заповнити описи значень 
--атрибутів екземплярів об'єктів.
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(1, 1, 8);
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(2, 1, 'Dye_hair');

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(3, 2, 7);
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(4, 2, 8);
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(5, 2, 750.00);
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(6, 2, 5);
    
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(7, 3, 6);
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(8, 3, 'Diana Kazakova');
INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
	VALUES(9, 3, 2);
    

--5.3 Модифікувати рішення завдання 4.3, отримавши колекцію екземплярів об'єктів за заданим
--значенням одного з атрибутів об'єктів.
SELECT List_Of_Services.NAME, 
    A.VALUE Employee
FROM OBJECTS List_Of_Services, OBJTYPE List_Of_Services_TYPE, ATTRIBUTES A
WHERE 
	List_Of_Services_TYPE.CODE = 'List_Of_Services'
	AND List_Of_Services_TYPE.OBJECT_TYPE_ID = List_Of_Services.OBJECT_TYPE_ID
	AND List_Of_Services.OBJECT_ID = A.OBJECT_ID
	AND A.ATTR_ID = 7;
/*
NAME                 EMPLOYEE
-------------------- ----------------------
Registration 1       6
*/
