name: SQLCodeConvention
on:
  push: 
    branches: 19-tasks-of-laboratory-work-10-1
jobs:
 _2sql:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout Code in Repository
    uses: "actions/checkout@v3"
  - name: Start SQL Linter
    run: |
      pip install sqlfluff
      sqlfluff lint $GITHUB_WORKSPACE/2.sql --dialect oracle
